// Auto-generated. Do not edit.
// RouterOutputs["github"]["getGithubRepositories"]

export type GithubGetGithubRepositories = Array<{
    id: number;
    node_id: string;
    name: string;
    full_name: string;
    license: null | {
        key: string;
        name: string;
        url: null | string;
        spdx_id: null | string;
        node_id: string;
        html_url?: undefined | string;
      };
    forks: number;
    permissions?: undefined | {
        admin: false | true;
        pull: false | true;
        triage?: undefined | false | true;
        push: false | true;
        maintain?: undefined | false | true;
      };
    owner: {
      name?: undefined | null | string;
      email?: undefined | null | string;
      login: string;
      id: number;
      node_id: string;
      avatar_url: string;
      gravatar_id: null | string;
      url: string;
      html_url: string;
      followers_url: string;
      following_url: string;
      gists_url: string;
      starred_url: string;
      subscriptions_url: string;
      organizations_url: string;
      repos_url: string;
      events_url: string;
      received_events_url: string;
      type: string;
      site_admin: false | true;
      starred_at?: undefined | string;
    };
    private: false | true;
    html_url: string;
    description: null | string;
    fork: false | true;
    url: string;
    archive_url: string;
    assignees_url: string;
    blobs_url: string;
    branches_url: string;
    collaborators_url: string;
    comments_url: string;
    commits_url: string;
    compare_url: string;
    contents_url: string;
    contributors_url: string;
    deployments_url: string;
    downloads_url: string;
    events_url: string;
    forks_url: string;
    git_commits_url: string;
    git_refs_url: string;
    git_tags_url: string;
    git_url: string;
    issue_comment_url: string;
    issue_events_url: string;
    issues_url: string;
    keys_url: string;
    labels_url: string;
    languages_url: string;
    merges_url: string;
    milestones_url: string;
    notifications_url: string;
    pulls_url: string;
    releases_url: string;
    ssh_url: string;
    stargazers_url: string;
    statuses_url: string;
    subscribers_url: string;
    subscription_url: string;
    tags_url: string;
    teams_url: string;
    trees_url: string;
    clone_url: string;
    mirror_url: null | string;
    hooks_url: string;
    svn_url: string;
    homepage: null | string;
    language: null | string;
    forks_count: number;
    stargazers_count: number;
    watchers_count: number;
    size: number;
    default_branch: string;
    open_issues_count: number;
    is_template?: undefined | false | true;
    topics?: undefined | string[];
    has_issues: false | true;
    has_projects: false | true;
    has_wiki: false | true;
    has_pages: false | true;
    has_downloads: false | true;
    has_discussions?: undefined | false | true;
    archived: false | true;
    disabled: false | true;
    visibility?: undefined | string;
    pushed_at: null | string;
    created_at: null | string;
    updated_at: null | string;
    allow_rebase_merge?: undefined | false | true;
    temp_clone_token?: undefined | string;
    allow_squash_merge?: undefined | false | true;
    allow_auto_merge?: undefined | false | true;
    delete_branch_on_merge?: undefined | false | true;
    allow_update_branch?: undefined | false | true;
    use_squash_pr_title_as_default?: undefined | false | true;
    squash_merge_commit_title?: undefined | "PR_TITLE" | "COMMIT_OR_PR_TITLE";
    squash_merge_commit_message?: undefined | "PR_BODY" | "COMMIT_MESSAGES" | "BLANK";
    merge_commit_title?: undefined | "PR_TITLE" | "MERGE_MESSAGE";
    merge_commit_message?: undefined | "PR_TITLE" | "PR_BODY" | "BLANK";
    allow_merge_commit?: undefined | false | true;
    allow_forking?: undefined | false | true;
    web_commit_signoff_required?: undefined | false | true;
    open_issues: number;
    watchers: number;
    master_branch?: undefined | string;
    starred_at?: undefined | string;
    anonymous_access_enabled?: undefined | false | true;
  }>;
